Feature/49 refactor mlflow azure
emkarcinos/AITech-flats pull request #66
Opened 2023-02-08 00:58 UTC by Adelionek

Trochę dużo się tutaj zadziało. Następne powinny być definitywnie mniejsze.

- Support dla MlFlow
- Refactor kodu - przeniesienie jupyterów do osobnych plików pythonowych i ekstrakcja wspólnych metod
- Refactor kodu v2 - utworzony config dla modeli i główna klasa do uruchamiania eksperymentów

2023-02-22 18:13 UTC, emkarcinos requested changes
## Dostosowanie istniejącego kodu do nowych zmian
Mieliśmy jakiś czas temu dyskusję na temat tego że nie zmieniamy starych jupyterów żeby działały z nowym kodem, natomiast teraz to zaczęło się wymykać spod kontroli, do tego stopnia że po paru tygodniach przerwy od projektu nie wiem, w którym pliku używamy najnowszych zmian a który nie działa. Dodatkowo jeżeli chcielibyśmy powtórzyć poprzednie eksperymenty, to nie bardzo mamy możliwość. Sądzę że powinniśmy doprowadzić historyczne jupytery do kodu po refactorach

## N pieczeni na jednym ogniu
Doceniam to że dużo dorzuciłeś do kodu, mamy dzięki temu lepsze wyniki, natomiast robienie code review i zarządzanie projektem stają się coraz trudniejsze. Nie wiem już tak naprawdę w jakim stanie jest teraz ten projekt, co mamy zrobione i w jakim stopniu. Ten kod do augmentacji danych jest dobrym przykładem - możemy teraz powiedzieć, ha, no Adam już to zrobił. Tylko, że tak naprawdę nie mamy z tego większych wniosków, nie wiemy co zadziałało a co nie. Dobrze byłoby skupić się porządnie nad jedną rzeczą którą robimy w danej chwili zamiast rozgrzebywać kilka innych, 'a bo tak przy okazji'. To jeżeli już jest taka sytuacja, to chociaż niech to się dzieje na osobnym branchu, gdzie możemy to osobno przetestować, zobaczyć wyniki, zrobić code review. Zostawiłem Ci teraz sporo komentarzy i domyślam się że samo ogarnięcie jak je teraz poprawić czy skomentować już może być trochę przytłaczające, bo dotykają 5 różnych obszarów. Przy robieniu tego review też miałem tak samo i ciężko mi się to robiło.

## Uwspólnienie kodu
Wydaje mi się, że powinniśmy pociągnąć to zadanie trochę dalej żeby mieć już gotowy framework który pozwoli nam szybko tworzyć eksperymenty. Na razie nadal potrzebujemy kopiować część logiki, co potem sprawia że na przykłąd utrzymywanie starych jupyterów po refactorach jest trudne. Nie mówiąc już o tym, że potem nie mam pewności czy na pewno tej mój model pójdzie do tego mlflow, czy może zły kod skopiowałem.

## Pylint
To narzędzie nie tylko ma sprawić że kod ładnie wygląda, ale też wykrywa błędy typu "u mnie działa", tak jak w przypadku tych importów, gdzie tutaj zależy tak naprawdę w jakim directory wykonasz skrypt, bo nie dorzuciłeś `__init__.py`. Jakby nie wyciszony warning, to pochyliłbyś się nad tym i znalazł błąd.

## Jupytery
Jaki jest ich obecnie stan? Przerzucamy się teraz na skrypty Pythonowe? W którymś jest zhardocowania ścieżka do Twojego folderu z dokumentami na lokalnym kompie

2023-02-22 18:13 UTC, emkarcinos commented on .pylintrc
> +        import-error
Nie wiem czy to dobrze że ten error jest wyciszany. Tym bardziej jeżeli pomaga, bo mi te importy faktycznie nie działają - folder `internal_modules` nie ma pliku `__init__.py` przez co interpreter nie traktuje go jako moduł. Patrząc na importy w pozostałych plikach widać, że chcemy żeby ten folder był traktowany jako moduł: 
```python3
import internal_modules.azure_workspace as azure_workspace
```

2023-02-22 18:13 UTC, emkarcinos commented on requirements.txt
> +pillow~=9.4.0
Brakuje https://pypi.org/project/azureml-core/
```suggestion
pillow~=9.4.0
azureml-core~=1.49.0
```
```
---> 26 from azureml.core import Workspace
ModuleNotFoundError: No module named 'azureml.core'
```

2023-02-22 18:13 UTC, emkarcinos commented on data/augmentation.py
> +    image = transforms.functional.adjust_saturation(image, 1.5)
Nie powinniśmy tutaj używać stałych wartości. 
Na wejściu możemy mieć obraz który na przykład jest już przejaskrawiony i przekontrastowany, te operacje jeszcze bardziej pogorszą wejście. 

Jest osobne zadanie na eksperymentowanie z agumentacją danych i sugerowałbym zrobić to osobno i poświęcić temu więcej czasu żeby to miało sens i na przykład rozszerzało dataset zamiast zmieniać każde zdjęcie.

2023-02-22 18:13 UTC, emkarcinos commented on data/loaders.py
> +    directories = os.listdir(input_dir)
Skąd ta zmiana? Wcześniej wszystko działało tak jak trzeba.

2023-02-22 18:13 UTC, emkarcinos commented on experiments/python_scripts/configs.py
> +RESNET_34_CONFIG = ExperimentConfig(
Wszystkie te configi wyglądają tak samo z wyjatkiem pojedynczych parametrów. Wyabstrachujmy wspólną część żeby nie trzeba było za każdym nowym eksperymentem duplikować kodu

2023-02-22 18:13 UTC, emkarcinos commented on data/augmentation.py
> +    image = transforms.functional.resize(image, (256, 256))
Rozmiar powinien być sparametryzowany - ja na przykład często odpalam modele na jakiś małych obrazkach żeby sprawdzić jak wszystko działa bez czekania 10 sekund na iterację

2023-02-22 18:13 UTC, emkarcinos commented on data/augmentation.py
> +    remove_ds(source_dir)
Jak tak bardzo nie chcesz tego folderu / pliku to może go po prostu usuń u siebie lokalnie? Już któryś raz widzę w kodzie ten DS Store. Ja też mam maca i mi się te foldery w ogóle nie tworzą.

2023-02-22 18:13 UTC, emkarcinos commented on data/augmentation.py
> +            if file.endswith(".jpg") and len(file) > 8:
Co to za magiczna ósemka?

2023-02-22 18:13 UTC, emkarcinos commented on data/augmentation.py
> +import os
Fajnie że już zacząłeś to ogarniać, ale wydaje mi się że lepiej chwycić porządnie jedną srokę za ogon zamiast próować robić wszystko na raz.

W takim stanie w jakim to teraz jest widziałbym jako early concept - wymaga to jeszcze dopracowania, przeprowadzenia jakiś eksperymentów, parametryzację i więcej rodzaji augmentacji. 

Moja sugestia to wynieść to poza zakres tego PRa, do jakiegoś PoC brancha podpiętego pod nowego taska z augmentacją. Co o tym sądzisz?

2023-02-22 18:13 UTC, emkarcinos commented on experiments/python_scripts/main.py
> +    def create_plots(self, test_dataset, full_dataset, classes, model):
Ta metoda powinna też tworzyć pozostałe wykresy, dorzućmy je tutaj.

2023-02-22 18:13 UTC, emkarcinos commented on experiments/python_scripts/main.py
> +        if model_name == "resnet34":
Zamiast przekazywać model_name jako parametr, który łatwo można pomylić, może po prostu sprawdzajmy typ instancji patametru `model`?

2023-02-22 18:13 UTC, emkarcinos commented on experiments/python_scripts/main.py
> +    def freeze_model(model, model_name, classes_count, device):
Może by to wynieść do osobnego pliku jako sama funkcja? Jak będziemy eksperymentować z innymi modelami to to się może rozrastać. Dodatkowo w tym pliku już jest sporo innej logiki która dotyczny stricte eksperymentów.

2023-02-22 18:13 UTC, emkarcinos commented on experiments/python_scripts/main.py
> +    def get_device():
Używamy tego już w wielu miejscach, w jupyterach itp, może przenieść to do osobnego pliku jako po prostu funkcja żeby zunifikować wybór urządzenia dla wszystkich plików?

2023-02-22 18:13 UTC, emkarcinos commented on experiments/python_scripts/main.py
> +    def run(self):
Nie bardzo rozumiem jak miałbym wykorzystywać tą klasę przy eksperymentach z innymi modelami.

Jeżeli już obraliśmy obiektowe podejście, ta klasa mogłaby być czymś na wzór klasy abstrakcyjnej, gdzie przy każdym eksperymencie mielibyśmy do zoverridowania kilka metod, takich jak:
- ładowanie datasetu / najlepiej jako dependency, kompozycja tutaj zadziała lepiej niż dziedziczenie, bo zazwyczaj będziemy chcieli wybrać logikę z już istniejących, i podmieniać sobie ją w ramach potrzeb, na przykład jak będziemy robić augmentację danych
- definicja modelu
- definicja parametrów modelu (optimizer,loss, epoki, lr, itp)

Teraz musiałbym zoverridować całą metodę `run` i zduplikować i tak te rzeczy które powinny być wspólne, czyli logowanie metryk, czy generowanie wykresów.

Podsumowując, z tej metody wynieść osobno logikę która ma być modyfikowana przez child classes, a samo run powinno je wykorzystywać w taki sposób żeby cały eksperyment przebiegał w kontrolowany sposób.

2023-02-22 18:13 UTC, emkarcinos commented on experiments/python_scripts/model_alpha_VGG19.py
> +# pylint: disable-all
Dlaczego?

2023-02-22 18:13 UTC, emkarcinos commented on experiments/python_scripts/model_alpha_VGG19.py
> +    os.path.join(os.path.realpath(__file__), "../../../")
Nie musimy tego tutaj robić, to było potrzebne tylko w przypadku jupytera, które mają jakiś dziwny kontekst interpretera. Ścieżki do modułów rozwiąże python (pamiętaj żeby dorzucić `__init__.py` do `internal_modules`

2023-02-22 18:13 UTC, emkarcinos commented on experiments/python_scripts/model_alpha_VGG19.py
> +    )
To już gdzieś było!

2023-02-22 18:13 UTC, emkarcinos commented on experiments/python_scripts/model_alpha_VGG19.py
> +if __name__ == "__main__":
Widzę że samemu nie czułeś się zachęcony żeby korzystać z tego co wcześniej zrobiłeś w `ExperimentRunner` :)

2023-02-23 13:40 UTC, Adelionek commented
Dzięki za tak porządne review. Szczerze nie spodziewałem się, że aż tak się do tego przyłożysz :). Nie sądziłem też, że tych nowych zmian jest aż tyle, chyba lekko straciłem rachubę.

Faktycznie, jak przejrzałem jeszcze raz całego PR'a to jest dużo zmian 'z dupy' które zostały zrobione 'po drodze'.  Wynikały one głównie z tego, że po ostatnim CR dodałem lokalnie dużo rzeczy, które były kluczowe do osiągnięcia efektów które mamy już wdrożone np. augmentacja, konwersja modelu do onnx itp. Totalnie się zgadzam, zrobił się syf i jest to totalnie nie wg procesu, kolejne będą mniejsze. Jednak mój plan był trochę inny. Chciałem dopiąć tego PR'a żeby wszystko co jest wdrożone było na mainie i później dopiero do tego porobić poprawki. Jest wiele podejść do tworzenia kodu, ja jestem zwolennikiem najpierw napisania działającego kodu a w kolejnym kroku 'upiększanie' go. 

ad Dostosowanie istniejącego kodu do nowych zmian
Na początku mieliśmy podejście 1 jupyter 1 model. Przy tak dużej ilości zmian jak mlflow, augmentacja, pylint ciężko jest trzymać je spójne, stąd przeniesienie kodu do plików pythonowych. Jak dla mnie to jupytery możemy albo wywalić z repo albo dodać je do gitignore i każdy niech sobie dostosowuje do swoich eksperymentów. Wszystkie pliki pythonowe w tym PR były up to date do wszystkich wprowadzonych zmian.

ad N pieczeni na 1 ogniu
Im sorrry. Już trochę odniosłem się do tego na wstępie. Docelowo będę o tym pamietać i będzie to bardziej granularne. Jednak musimy znaleźć jakiś złoty środek między jakością kodu a jego efektywnością. Podejście w którym robimy merge do maina raz na miesiąc bo próbujemy przy każdym mergu mieć idealnie uporządkowany kod nie jest efektywne. Szczególnie, że i tak mergujemy kod do maina wiedząc, że w przyszłości będzie musiał być on jeszcze zrefactorowany. Brakuje mi tu trochę gitflow i dodatkowego brancha np dev/qa do którego byśmy wrzucali mniej dopracowane zmiany (ale działające). Wtedy moglibyśmy ustalić, że to co trafia na dev/qa jest już odwzorowane na azure/froncie/mlflow a to co trafia do maina jest już docelowym rozwiązaniem które jest zrefactorowane (generyczny, uporzątkowany kod itp). Brakuje nam jedynie dodatkowego środowiska na Azure ale w teorii można to ogarnąć. 
Przykład z augmentacją jest bardzo trafny. Powinno być to zrobione na osobym branchu. Tak samo jak wprowadzenie configu.

ad Uwspólnienie kodu
Jak najbardziej jestem za. Tylko co jest ważniejsze? Zebranie w końcu całego działającego kodu w całość i następnie zajęcie się naprawianiem/abstrachowaniem kodu, czy robienie tego upfront? Myślę, że powinniśmy korzystać z plików pythonowych, tak jak wcześniej wspomniałem. 

ad Pylint
Jeśli o to chodzi to szczerze nie wiedziałem, że powodem jest plik __init__.py. Pylint rzucał błędy gdy importowałem biblioteki związane z azure.

ad Jupytery
Zhardcodowane ścieżki wyrzucę, były użyte tylko w ostatnim kroku do 'sample predict image' gdzie podawałem ścieżkę do lokalnego zdjęcia i modelu. Wywale to. Przerzucamy się na pliki pythonowe.

Tak jak napisałem na telegramie, chyba będzie sensowniej jak to rozbije to na mniejsze PR'y co sam zaproponowałeś.

2023-02-23 13:51 UTC, Adelionek commented
Dodatkowo myślę, że uniknęli byśmy takiego rozjazdu w podejściu do repo gdybyśmy faktycznie się spotykali raz w tygodniu i gadali o tych zmianach nad którymi pracujemy. Bez żalu, ale przez pewien czas czułem że robie większość jeśli chodzi o tą część backendowo/ML'ową. Spowodowało to trochę samowolkę i zacząłem dostosowywać kod pod siebie, nie zastanawiając się bardzo czy będzie to też działać po waszej stronie. 

Zbliża się weekend, ja będę w stanie wygospodarować pare godzin. Możemy się spotkać i porozmawiać, ustalić jakie mamy flow, gdzieś to udokumentować. Trochę się czuję jak bym zmarnował dużą część swojego czasu wnosząc te poprawki i update'y bo i tak teraz trzeba je przerobić.

2023-02-26 15:03 UTC, Adelionek commented on requirements.txt
> +pillow~=9.4.0
Dodane

2023-02-26 15:06 UTC, Adelionek commented on .pylintrc
> +        import-error
Init dodadny

2023-02-26 16:23 UTC, Adelionek commented on experiments/python_scripts/model_alpha_VGG19.py
> +    os.path.join(os.path.realpath(__file__), "../../../")
Zmienione

2023-08-04 21:29 UTC, merged